import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainLayout from "@/layouts/mainLayout";

const youth = localFont({
  src: [
    {
      path: "../public/fonts/Youth-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Youth-Medium.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/Youth-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "SFÉRA - interní grafický manuál",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={`${youth.className} antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
